version: "3.9"

services:
  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend:/service
    depends_on:
      - backend

  backend:
    build:
      context: backend
    container_name: portfolio_backend
    volumes:
      - ./backend:/service

  reverse-proxy:
    build:
      context: nginx
      dockerfile: dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/configs:/etc/nginx/conf.d

networks:
  public:
  private:

volumes:
  back-notused:
  db-data:
